import { Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import './globals.css';

const worksans = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={worksans.className}>
        <Theme accentColor='mint' grayColor='slate' scaling='95%'>
          {children}
        </Theme>
      </body>
    </html>
  );
}
