version: '3.8' # Version of the docker-compose file

services:
  backend:
    build:
      context: ./Backend # Path to the backend Dockerfile
    container_name: backend
    ports:
      - '8000:8000' # Host machine : Container
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend # Path to the frontend Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app 
      - /app/node_modules
      - /app/.next
    command: npm run dev
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
