# Base image
FROM python:3.11-slim

ENV PYTHONUNBUFFERED 1

RUN apt-get update
RUN apt-get install libpq-dev gcc -y

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "manage.py", "runserver_plus", "0.0.0.0:8000", "--reloader-type", "watchdog"]
