# Generated by Django 4.2.14 on 2024-08-08 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordly_app', '0002_category_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 1, 56, 58, 78577, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='word',
            name='next_memory_test_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 1, 56, 58, 78623, tzinfo=datetime.timezone.utc)),
        ),
    ]
