name: Backend

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and run Docker Compose
      run: |
        docker compose build
        docker compose up -d

    - name: Run Django tests
      env:
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        DB_PORT=5432
        DB?URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:${{ secrets.DB_PORT }}/${{ secrets.POSTGRES_DB }}
      run: |
        docker exec -it backend bash -c 'python manage.py test wordly_app.tests'

    - name: Stop Docker Compose
      if: always()
      run: docker compose down
