# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    name: Deploy Storybook to chromatic
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ja/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_SECRET }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: cd Frontend && npm install
      - run: cd Frontend && npm run build-storybook
