# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

defaults:
  run:
    working-directory: Frontend

# List of jobs
jobs:
  chromatic-deployment:
    name: Deploy Storybook to chromatic
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run Chromatic
        uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ja/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_SECRET }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: Frontend
